
name: google_mlkit_barcode_scanning
description: A Flutter plugin for Google's ML Kit Barcode Scanning.
version: 0.9.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons:
    path: ../google_mlkit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_barcode_scanning
        pluginClass: GoogleMlKitBarcodeScanningPlugin
      ios:
        pluginClass: GoogleMlKitBarcodeScanningPlugin
