// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARlaUTtOCnZNX7sO1EEH8C1bWKqyLHPYY',
    appId: '1:762151048911:web:0f576854415b7f2a74c9ba',
    messagingSenderId: '762151048911',
    projectId: 'oneid-pro-f79cb',
    authDomain: 'oneid-pro-f79cb.firebaseapp.com',
    storageBucket: 'oneid-pro-f79cb.firebasestorage.app',
    measurementId: 'G-69ZB3DYM3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqCy9kZ91663d6RhctHRHrgOla3aBKu1s',
    appId: '1:762151048911:android:cd43098f594c312d74c9ba',
    messagingSenderId: '762151048911',
    projectId: 'oneid-pro-f79cb',
    storageBucket: 'oneid-pro-f79cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4vz9YPLiwuP0Nwnf4Lr1u7tnQ9aP8H0w',
    appId: '1:762151048911:ios:0fd218c15dfe735f74c9ba',
    messagingSenderId: '762151048911',
    projectId: 'oneid-pro-f79cb',
    storageBucket: 'oneid-pro-f79cb.firebasestorage.app',
    iosBundleId: 'com.example.oneid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4vz9YPLiwuP0Nwnf4Lr1u7tnQ9aP8H0w',
    appId: '1:762151048911:ios:0fd218c15dfe735f74c9ba',
    messagingSenderId: '762151048911',
    projectId: 'oneid-pro-f79cb',
    storageBucket: 'oneid-pro-f79cb.firebasestorage.app',
    iosBundleId: 'com.example.oneid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARlaUTtOCnZNX7sO1EEH8C1bWKqyLHPYY',
    appId: '1:762151048911:web:d7b2a81c16588b1f74c9ba',
    messagingSenderId: '762151048911',
    projectId: 'oneid-pro-f79cb',
    authDomain: 'oneid-pro-f79cb.firebaseapp.com',
    storageBucket: 'oneid-pro-f79cb.firebasestorage.app',
    measurementId: 'G-YHVZ0LJV2S',
  );
}
